services:
  - type: web
    name: route53-clone-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./route53.db
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: BACKEND_CORS_ORIGINS
        sync: false
